import React from "react";
import Head from "next/head";
import Layout from "@/components/Layout";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { easeInOut, motion } from "framer-motion";
import TransitionEffect from "@/components/TransitionEffect";

const Article = ({ title, date, link }) => {
  return (
    <motion.li
      initial={{ y: 200 }}
      whileInView={{ y: 0, transition: { duration: 0.7, ease: easeInOut } }}
      viewport={{ once: true }}
      className="relative w-full p-4 py-6 my-4 rounded-xl flex items-center justify-between bg-light text-dark first:mt-0 border border-solid border-dark
      border-r-4 border-b-4 dark:border-light dark:bg-dark dark:text-light
      sm:flex-col
    "
    >
      <Link
        href={link}
        target="_blank"
        className="capitalize text-xl font-semibold hover:underline"
      >
        {title}
      </Link>
      <span className="text-primary font-semibold pl-4 sm:self-start sm:pl-0 xs:text-sm">
        {date}
      </span>
    </motion.li>
  );
};

const articles = () => {
  return (
    <>
      <Head>
        <title>Huveyda Tukle | Articles Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="w-full mb-16 flex flex-col items-center overflow-hidden dark:text-light">
        <Layout className="pt-16">
          <AnimatedText
            text="Explore, Read, Evolve."
            className="mb-16 lg:!text-7xl sm:mb-8 sm:!text-6xl xs:!text-4xl"
          />
          <h2 className="font-bold text-3xl w-full text-center my-16 lg:gap-8 md:grid-cols-1 md:gap-y-16">
            All Articles
          </h2>
          <ul>
            <Article
              title="8 React Open-Source projects to learn and become a React.js Developer"
              date="July, 2022"
              link="https://medium.com/datadriveninvestor/8-react-open-source-projects-to-learn-and-become-a-react-js-developer-8376107730c4"
            />
            <Article
              title="Implementing Magic Link Email Authentication in NextJS + NodeJS Applications"
              date="October, 2023"
              link="https://medium.com/@radzion/implementing-magic-link-email-authentication-in-nextjs-nodejs-applications-f09c97c5d64b"
            />
          </ul>
        </Layout>
      </main>
    </>
  );
};

export default articles;
